module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.Main
import Evergreen.V3.Main.Pages.Model
import Evergreen.V3.Main.Pages.Msg
import Evergreen.V3.Pages.Game10x10
import Evergreen.V3.Pages.Game3x3
import Evergreen.V3.Pages.Game5x5
import Evergreen.V3.Pages.Home_
import Evergreen.V3.Pages.NotFound_
import Evergreen.V3.Shared
import Evergreen.V3.Shared.Model
import Evergreen.V3.Shared.Msg
import Evergreen.V3.Types
import Evergreen.V4.Main
import Evergreen.V4.Main.Pages.Model
import Evergreen.V4.Main.Pages.Msg
import Evergreen.V4.Pages.Game10x10
import Evergreen.V4.Pages.Game3x3
import Evergreen.V4.Pages.Game5x5
import Evergreen.V4.Pages.Home_
import Evergreen.V4.Pages.NotFound_
import Evergreen.V4.Shared
import Evergreen.V4.Shared.Model
import Evergreen.V4.Shared.Msg
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Main_Model : Evergreen.V3.Main.Model -> Evergreen.V4.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V3.Main.Msg -> Evergreen.V4.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V3.Main.UrlRequested p0 ->
            Evergreen.V4.Main.UrlRequested p0

        Evergreen.V3.Main.UrlChanged p0 ->
            Evergreen.V4.Main.UrlChanged p0

        Evergreen.V3.Main.Page p0 ->
            Evergreen.V4.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V3.Main.Layout p0 ->
            Evergreen.V4.Main.Layout p0

        Evergreen.V3.Main.Shared p0 ->
            Evergreen.V4.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V3.Main.Batch p0 ->
            Evergreen.V4.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V3.Main.Pages.Model.Model -> Evergreen.V4.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V3.Main.Pages.Model.Home_ p0 ->
            Evergreen.V4.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V3.Main.Pages.Model.Game10x10 p0 ->
            Evergreen.V4.Main.Pages.Model.Game10x10 (p0 |> migrate_Pages_Game10x10_Model)

        Evergreen.V3.Main.Pages.Model.Game3x3 p0 ->
            Evergreen.V4.Main.Pages.Model.Game3x3 (p0 |> migrate_Pages_Game3x3_Model)

        Evergreen.V3.Main.Pages.Model.Game5x5 p0 ->
            Evergreen.V4.Main.Pages.Model.Game5x5 (p0 |> migrate_Pages_Game5x5_Model)

        Evergreen.V3.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V4.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V3.Main.Pages.Model.Redirecting_ ->
            Evergreen.V4.Main.Pages.Model.Redirecting_

        Evergreen.V3.Main.Pages.Model.Loading_ ->
            Evergreen.V4.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V3.Main.Pages.Msg.Msg -> Evergreen.V4.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V3.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V4.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V3.Main.Pages.Msg.Game10x10 p0 ->
            Evergreen.V4.Main.Pages.Msg.Game10x10 (p0 |> migrate_Pages_Game10x10_Msg)

        Evergreen.V3.Main.Pages.Msg.Game3x3 p0 ->
            Evergreen.V4.Main.Pages.Msg.Game3x3 (p0 |> migrate_Pages_Game3x3_Msg)

        Evergreen.V3.Main.Pages.Msg.Game5x5 p0 ->
            Evergreen.V4.Main.Pages.Msg.Game5x5 (p0 |> migrate_Pages_Game5x5_Msg)

        Evergreen.V3.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V4.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Game10x10_Model : Evergreen.V3.Pages.Game10x10.Model -> Evergreen.V4.Pages.Game10x10.Model
migrate_Pages_Game10x10_Model old =
    { clickedCells = old.clickedCells
    , targetNumbers = []
    , targetNumber = old.targetNumber
    , timer = old.timer
    , isRunning = old.isRunning
    , mistakes = old.mistakes
    , gameComplete = old.gameComplete
    , hoveredCell = old.hoveredCell
    , wrongCell = old.wrongCell
    , showPenalty = old.showPenalty
    , playerName = old.playerName
    , scoreSaved = old.scoreSaved
    }


migrate_Pages_Game10x10_Msg : Evergreen.V3.Pages.Game10x10.Msg -> Evergreen.V4.Pages.Game10x10.Msg
migrate_Pages_Game10x10_Msg old =
    case old of
        Evergreen.V3.Pages.Game10x10.CellClicked p0 p1 ->
            Evergreen.V4.Pages.Game10x10.CellClicked p0 p1

        Evergreen.V3.Pages.Game10x10.GotTargetNumber p0 ->
            Evergreen.V4.Pages.Game10x10.GotShuffledTargets [ p0 ]

        Evergreen.V3.Pages.Game10x10.Tick ->
            Evergreen.V4.Pages.Game10x10.Tick

        Evergreen.V3.Pages.Game10x10.CellHovered p0 p1 ->
            Evergreen.V4.Pages.Game10x10.CellHovered p0 p1

        Evergreen.V3.Pages.Game10x10.CellUnhovered ->
            Evergreen.V4.Pages.Game10x10.CellUnhovered

        Evergreen.V3.Pages.Game10x10.ClearWrongCell ->
            Evergreen.V4.Pages.Game10x10.ClearWrongCell

        Evergreen.V3.Pages.Game10x10.ClearPenalty ->
            Evergreen.V4.Pages.Game10x10.ClearPenalty

        Evergreen.V3.Pages.Game10x10.PlayerNameChanged p0 ->
            Evergreen.V4.Pages.Game10x10.PlayerNameChanged p0

        Evergreen.V3.Pages.Game10x10.SaveScore ->
            Evergreen.V4.Pages.Game10x10.SaveScore

        Evergreen.V3.Pages.Game10x10.GotTimestamp p0 ->
            Evergreen.V4.Pages.Game10x10.GotTimestamp p0


migrate_Pages_Game3x3_Model : Evergreen.V3.Pages.Game3x3.Model -> Evergreen.V4.Pages.Game3x3.Model
migrate_Pages_Game3x3_Model old =
    { clickedCells = old.clickedCells
    , targetNumbers = []
    , targetNumber = old.targetNumber
    , timer = old.timer
    , isRunning = old.isRunning
    , mistakes = old.mistakes
    , gameComplete = old.gameComplete
    , hoveredCell = old.hoveredCell
    , wrongCell = old.wrongCell
    , showPenalty = old.showPenalty
    , playerName = old.playerName
    , scoreSaved = old.scoreSaved
    }


migrate_Pages_Game3x3_Msg : Evergreen.V3.Pages.Game3x3.Msg -> Evergreen.V4.Pages.Game3x3.Msg
migrate_Pages_Game3x3_Msg old =
    case old of
        Evergreen.V3.Pages.Game3x3.CellClicked p0 p1 ->
            Evergreen.V4.Pages.Game3x3.CellClicked p0 p1

        Evergreen.V3.Pages.Game3x3.GotTargetNumber p0 ->
            Evergreen.V4.Pages.Game3x3.GotShuffledTargets [ p0 ]

        Evergreen.V3.Pages.Game3x3.Tick ->
            Evergreen.V4.Pages.Game3x3.Tick

        Evergreen.V3.Pages.Game3x3.CellHovered p0 p1 ->
            Evergreen.V4.Pages.Game3x3.CellHovered p0 p1

        Evergreen.V3.Pages.Game3x3.CellUnhovered ->
            Evergreen.V4.Pages.Game3x3.CellUnhovered

        Evergreen.V3.Pages.Game3x3.ClearWrongCell ->
            Evergreen.V4.Pages.Game3x3.ClearWrongCell

        Evergreen.V3.Pages.Game3x3.ClearPenalty ->
            Evergreen.V4.Pages.Game3x3.ClearPenalty

        Evergreen.V3.Pages.Game3x3.PlayerNameChanged p0 ->
            Evergreen.V4.Pages.Game3x3.PlayerNameChanged p0

        Evergreen.V3.Pages.Game3x3.SaveScore ->
            Evergreen.V4.Pages.Game3x3.SaveScore

        Evergreen.V3.Pages.Game3x3.GotTimestamp p0 ->
            Evergreen.V4.Pages.Game3x3.GotTimestamp p0


migrate_Pages_Game5x5_Model : Evergreen.V3.Pages.Game5x5.Model -> Evergreen.V4.Pages.Game5x5.Model
migrate_Pages_Game5x5_Model old =
    { clickedCells = old.clickedCells
    , targetNumbers = []
    , targetNumber = old.targetNumber
    , timer = old.timer
    , isRunning = old.isRunning
    , mistakes = old.mistakes
    , gameComplete = old.gameComplete
    , hoveredCell = old.hoveredCell
    , wrongCell = old.wrongCell
    , showPenalty = old.showPenalty
    , playerName = old.playerName
    , scoreSaved = old.scoreSaved
    }


migrate_Pages_Game5x5_Msg : Evergreen.V3.Pages.Game5x5.Msg -> Evergreen.V4.Pages.Game5x5.Msg
migrate_Pages_Game5x5_Msg old =
    case old of
        Evergreen.V3.Pages.Game5x5.CellClicked p0 p1 ->
            Evergreen.V4.Pages.Game5x5.CellClicked p0 p1

        Evergreen.V3.Pages.Game5x5.GotTargetNumber p0 ->
            Evergreen.V4.Pages.Game5x5.GotShuffledTargets [ p0 ]

        Evergreen.V3.Pages.Game5x5.Tick ->
            Evergreen.V4.Pages.Game5x5.Tick

        Evergreen.V3.Pages.Game5x5.CellHovered p0 p1 ->
            Evergreen.V4.Pages.Game5x5.CellHovered p0 p1

        Evergreen.V3.Pages.Game5x5.CellUnhovered ->
            Evergreen.V4.Pages.Game5x5.CellUnhovered

        Evergreen.V3.Pages.Game5x5.ClearWrongCell ->
            Evergreen.V4.Pages.Game5x5.ClearWrongCell

        Evergreen.V3.Pages.Game5x5.ClearPenalty ->
            Evergreen.V4.Pages.Game5x5.ClearPenalty

        Evergreen.V3.Pages.Game5x5.PlayerNameChanged p0 ->
            Evergreen.V4.Pages.Game5x5.PlayerNameChanged p0

        Evergreen.V3.Pages.Game5x5.SaveScore ->
            Evergreen.V4.Pages.Game5x5.SaveScore

        Evergreen.V3.Pages.Game5x5.GotTimestamp p0 ->
            Evergreen.V4.Pages.Game5x5.GotTimestamp p0


migrate_Pages_Home__Model : Evergreen.V3.Pages.Home_.Model -> Evergreen.V4.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V3.Pages.Home_.Msg -> Evergreen.V4.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V3.Pages.Home_.Never ->
            Evergreen.V4.Pages.Home_.Never


migrate_Pages_NotFound__Model : Evergreen.V3.Pages.NotFound_.Model -> Evergreen.V4.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V3.Pages.NotFound_.Msg -> Evergreen.V4.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V3.Pages.NotFound_.NoOp ->
            Evergreen.V4.Pages.NotFound_.NoOp


migrate_Shared_Model : Evergreen.V3.Shared.Model -> Evergreen.V4.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V3.Shared.Model.Model -> Evergreen.V4.Shared.Model.Model
migrate_Shared_Model_Model old =
    old


migrate_Shared_Msg : Evergreen.V3.Shared.Msg -> Evergreen.V4.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V3.Shared.Msg.Msg -> Evergreen.V4.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V3.Shared.Msg.GotLeaderboards p0 ->
            Evergreen.V4.Shared.Msg.GotLeaderboards p0
